# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show file structure (debug)
        run: ls -la

      - name: Run custom task
        run: echo "This is a placeholder — replace with actual build or test steps."
